### ISSUE TITLE
[3.0] What if data are delete from DB but not Algolia

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/search-bundle#162] opened 2017-12-05 10:51 UTC
When you use the `search` method, here is what happens:

1. Search in algolia for matching records
2. Use the `objectID` to create a doctrine collection (so data are pulled from the database)
3. Drop algolia's response (if you want algolia's response, use `rawSearch`)

```php
$posts = $indexManager->search('', Post::class, $em);
```

It could happens that something was found in Algolia but was deleted from the database for some reasons. In this case, we get a null entry in the collection. It makes the collection annoying to work with because you usually only expect entity object.

<img width="275" alt="impossible_to_access_an_attribute___title___on_a_null_variable___500_internal_server_error_" src="https://user-images.githubusercontent.com/1525636/33321019-5ee90c86-d444-11e7-8b80-9ba630efe032.png">

I'm in favor of removing the null entry from the collection, so you don't get unexpected behavior. But I think it would be nice to warn someone about the inconsistency. 

Should we: 
- Add something to the logs
- Delete object from Algolia automatically (not in favor of this one :D)
- Ignore it

**Comment by tristanbes** [comment] 2017-12-05 12:22
I'm not sure I understand what you're trying to explain.

**Comment by julienbourdeau** [comment] 2017-12-06 09:43
I rephrased it, I hope it's clearer.

**Comment by tristanbes** [comment] 2017-12-06 10:30
Well i'm going to vote for :
1. Add to the logs
2. Display information in the debug bar in a brand new shiny Algolia Collector
3. Ignore it

**Comment by nunomaduro** [comment] 2019-06-05 08:21
This issue is from year ago.

Action: Check if the problem still exists. And if exists: Add something to the logs, and create an issue that targets the next major version to solve this.

**Comment by julienbourdeau** [comment] 2019-06-05 14:58
I think the current state is just to ignore it. I `filter()` the collection so all null values are removed. In the end, I think it's fine.

Reindexing regularily is highly recommended by the way.

**Comment by tristanbes** [comment] 2019-06-05 15:26
then make it a free operation :p (if not possible, don't loose our indexing credit each month). I have huge data set, and each time I want to clear algolia to reindex the whole set, but I don't want to endup paying extra :(

(because sometimes algolia connexion time out and I have things in DB that doesn't exist on Algolia)

**Comment by chloelbn** [comment] 2019-06-19 08:11
I've checked the issue and could not reproduce the bug. This seems to have been fixed now. Please make sure you're using the latest version and don't hesitate to reopen this issue if they are problems remaining. Thanks!

**Closed** 2019-06-19 08:12 UTC
Labels: Bug
